version: '3'
services:
  b1:
    image: b1
    build:
      context: .
      dockerfile: Dockerfile1
    volumes:
      - postgres_data:/test/

  b2:
    build:
      context: .
      dockerfile: Dockerfile2

  b3:
    build:
      context: .
      dockerfile: Dockerfile3
    volumes:
      - postgres_data:/test/

volumes:
    postgres_data:
